#!/usr/bin/sh

set -e

confdir='.config/'
localdir='.local/'

checkAndInstallDir() {
  if [ -d $1 ]; then
    cp $1 $2 -r
  fi
}

checkAndInstallFile() {
  if [ -e $1 ]; then
    cp $1 $2
  fi
}

if ! [ -d $confdir ]; then
  mkdir $confdir
fi

if ! [ -d $localdir ]; then
  mkdir $localdir
fi

checkAndInstallFile ~/.bashrc .
checkAndInstallFile ~/.gitconfig .

checkAndInstallDir ~/.config/alacritty/ ./$confdir
checkAndInstallDir ~/.config/clangd/ ./$confdir
checkAndInstallDir ~/.config/nvim/ ./$confdir
checkAndInstallDir ~/.config/mpv/ ./$confdir
checkAndInstallFile ~/.config/xdg-terminals.list ./$confdir

checkAndInstallDir ~/.local/bin/ ./$localdir