#!/usr/bin/sh

set -e

confdir='.config/'

checkAndInstallDir() {
  if [ -d $1 ]; then
    cp $1 $2 -r
  fi
}

checkAndInstallFile() {
  if [ -e $1 ]; then
    cp $1 $2
  fi
}

if ! [ -d $confdir ]; then
  mkdir $confdir
fi

checkAndInstallDir ~/.config/alacritty/ ./$confdir
checkAndInstallDir ~/.config/clangd/ ./$confdir
checkAndInstallDir ~/.config/nvim/ ./$confdir
checkAndInstallDir ~/.config/mpv/ ./$confdir
checkAndInstallFile ~/.config/xdg-terminals.list ./$confdir
checkAndInstallFile ~/.bashrc .
checkAndInstallFile ~/.gitconfig .
