CompileFlags:
    Add:
        [
            -std=c++20,
            -Wall,
            -Wextra,
            -Wpedantic,
            -Wshadow,
            -Wno-unknown-warning-option,
            -Wno-unknown-pragmas,
        ]
