import = [ "~/.config/alacritty/themes/everforest_dark.toml" ]

[window]
opacity = 0.8

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "None"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "SauceCodeProNerdFont", style = "Regular" }
size = 17.0

