import = [ "~/.config/alacritty/themes/catppuccin-frappe.toml" ]

[window]
opacity = 1

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Dark"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "SauceCodeProNerdFont", style = "Regular" }
size = 18.0

